# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 946b0cc25326f811921239ae41b0d373c3e5a7434d54dab54f3da965aa1e73e55bba985943d43658ad4fc743446242a2c3483f81e4cbbabb126f207f52b7f9e4

test:
  secret_key_base: 9af2fd501b15d858b3a9fd81c9f2737ac831178f69ecd0d1cb9cceb10055ca32c5e3c1363256db37c53d2b6bc729895425dd90c0c54e1c254f0cad3a2297348b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
